### ISSUE TITLE
v5.208 released with doze fix

### ISSUE THREAD

**Issue by aquatix** [G00fY2/k-9_material_design#4]
I appreciate your (w|f)ork a lot and use it daily.

I recently noticed that K9 released v5.208 with a fix for recovering from doze, which affects my phone (it sometimes does not synchronise for over a day, until I manually start it).

If you have the time, could you update your fork to v5.208?

Bonus would be if you try your hand at v5.300, as that seems to be a lot more up-to-date with their master branch, but it's flagged pre-release for a reason.

Much appreciated either way!

**Comment by G00fY2** [comment]
Synced with original remote 6cab2c72c2ae77a5610b6027310e4a19d30ae329

**Comment by aquatix** [comment]
Seems to work great here, thanks very much for the update!

**Comment by G00fY2** [comment]
After a week using the new version I switched back to 5.207. Been using the app on my Pixel with Android 8 and didn't receive Push notifications at all. So I'm thinking about deleting the last release.

**Comment by aquatix** [comment]
Odd, seems to work here, but will monitor on my 6P with Oreo

**Comment by ghost** [comment]
ok for me too on Asus

**Comment by G00fY2** [comment]
After some days of using, IMAP IDLE is working like before. I forget to exclude K9 from doze in the Android app settings (which i did before and recommend!).
